# Generated by Django 2.2.5 on 2019-10-13 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191013_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default=1, max_length=50, verbose_name='имя автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_float',
            field=models.CharField(default=1, max_length=50, verbose_name='floats'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_int',
            field=models.CharField(default=1, max_length=50, verbose_name='ints'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_string',
            field=models.CharField(default=1, max_length=50, verbose_name='strings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default=1, max_length=200, verbose_name='текст комментария'),
            preserve_default=False,
        ),
    ]
