# Generated by Django 2.2.5 on 2019-10-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191013_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_float',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_int',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_string',
        ),
    ]
