# Generated by Django 2.2.5 on 2019-12-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20191013_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField(verbose_name='Полное имя студента')),
                ('student_course', models.CharField(max_length=20, verbose_name='Курс студента')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=200, verbose_name='имя автора'),
        ),
    ]
