# Generated by Django 2.2.5 on 2019-12-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20191210_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='delete',
            field=models.CharField(default=0, max_length=10, verbose_name='Remove'),
            preserve_default=False,
        ),
    ]
